### ISSUE TITLE
Hashtable - tr1/unordered_map not found error 

### ISSUE THREAD

**Issue by ykcai** [hyperledger/composer-sample-networks#93]
Got this error following the documentation for Developer Guide https://hyperledger.github.io/composer/tutorials/developer-guide.html

```
my-network npm install hashtable
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> hashtable@2.0.2 install /Users/michaelcai/Desktop/GiveBack/my-network/node_modules/hashtable
> node-gyp configure build

  CXX(target) Release/obj.target/native/src/hashtable.o
In file included from ../src/hashtable.cpp:1:
../src/hashtable.h:7:10: fatal error: 'tr1/unordered_map' file not found
#include <tr1/unordered_map>
         ^
1 error generated.
make: *** [Release/obj.target/native/src/hashtable.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/michaelcai/Desktop/GiveBack/my-network/node_modules/hashtable
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelcai/.npm/_logs/2017-09-13T19_18_13_771Z-debug.log 
```

If anyone has seen this error just run

 ```npm install "https://github.com/fabrice102/node-hashtable.git"  ```

And then run 

```npm install```  on the directory

**Comment by einarpersson** [comment]
+1

Thanks for the help! 

But following the official dev tutorial step by step should just work!

**Comment by AnthonyLimo** [comment]
Thanks man! Helped loads!

**Comment by hubaokun** [comment]
thank you！
